/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bil481hw1part2;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }
    //public static void method4Parameter(Arraylist<Integer> aList,Integer i, )
    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
